### ISSUE TITLE
Hvordan bruke import i node og ikke require

### ISSUE THREAD

**Issue by terchris** [tompi/novalidation#3]
Hei
Måtte bytte fra å laste inn med require til import.
Hvordan gjør man det med novalidation ?

import { NoValidation } from "novalidation"; eller import { orgNummer } from "novalidation";
fungerer ikke. 

mvh
Terje

**Comment by tompi** [comment]
Hei, beklager treigt svar. Oppdaterte readme.
TLDR: skal funke å gjøre
```js
import NoValidation from 'novalidation';
var gyldigFnr = NoValidation.fodselsNummer("12345678901");
```
